### ISSUE TITLE
Only write files with modified tags

### ISSUE THREAD

**Issue by khumba** [ncmpcpp/ncmpcpp#215]
Hello, firstly thanks for this awesome music player.

I have some WebM files in my music collection alongside MP3s and such which MPD plays just fine, however ncmpcpp's tag editor can't be used to modify the tags even of the MP3s in a directory containing WebMs, (if I understand correctly) because ncmpcpp appears to rewrite all files in the directory, and Taglib doesn't support writing WebM's metadata format[1].  WebM tag support aside, it would be great to be able to retag these MP3s without moving or keeping them elsewhere on disk.

[1] https://mail.kde.org/pipermail/taglib-devel/2013-January/002424.html

**Comment by dubcusb** [comment]
I had a similar issue with the overwriting. In my case this caused trouble because I couldn't use rsync to keep 2 folders up to date without having to send _all_ the files.
I've found a solution (workaround?) for this: **Select only the files you want to write to in the tag editor**, as in, do a visual selection and then save.
I know this issue is old, but it's the only thing I came across with when I wanted to fix this, so I might as well write the solution I found here for people who also need it.
