### ISSUE TITLE
[FEATURE] Check if song is on a playlist or list what  playlists a song is on. 

### ISSUE THREAD

**Issue by fullstopslash** [ncmpcpp/ncmpcpp#478]
It's currently unclear to me if there's an easy way to check if the currently playing song is on a specific playlist, or any of my playlists.  My current method  is to manually search each of my playlists, and as you can imagine it gets tedious rather quickly. If anyone has run into this and has come up with a solution I'd love to hear it! 

I can Imagine one solution where when a user summons the information screen with "i" on a song the player checks playlists lists the song shows up in.  However, that seems like it'd be a super resource intensive task. 

The alternative I'm considering is to use custom id3 tags _/as/_ smart playlists. Obviously this is remarkably easier for the devs as it would require nothing on their part, and fairly minimal effort on my part. 

Anyway I'd love to hear if someone's dealt with this before!

**Comment by Randoragon** [comment]
There is a way - when in playlist view, repeatedly press the `jump_to_playing_song` key (bound to `o` by default) to cycle through the current song's appearances in all playlists. If you have a large number of playlists (or very long playlists), this feature does not scale well and there is noticeable delay (I assume due to the linear search required). But for simple tasks it's perfect.
