### ISSUE TITLE
ncmpcpp fetches blank lyrics [BUG]

### ISSUE THREAD

**Issue by o0nd7ots** [ncmpcpp/ncmpcpp#570]
**Describe the bug**
When I press _L_ it displays "Fetching lyrics from azlyrics.com" for less than a second, and then the screen goes blank (see screenshot 1) and produces an empty lyrics file.

For Genious it produces some notes about how to format lyrics. Providers like mmusixmatch or tekstowo work fine

**To Reproduce**
1. Get mpd and ncmpcpp running
2. Play any FLAC file  with vaild metadata
3. Press _L_
4. You see the bug

**Expected behavior**
ncmpcpp downloads the lyrics to lyrics directory and displays them in the program

**Screenshots/Logs**
Screen 1: ncmpcpp second after pressing L on a well known song
![image](https://user-images.githubusercontent.com/124466962/232298376-cacba64f-5c2b-4b93-aed3-00447c3c49ec.png)

Screen 2: Info of the played file in kid3
![image](https://user-images.githubusercontent.com/124466962/232298919-4779ba9d-3907-4bdb-8d5e-5600a03cf32f.png)

Screen 3: showing the lyrics/ folder contents  (my lyrics forlder is /tmp/lyrics)
![image](https://user-images.githubusercontent.com/124466962/232300831-17fb65a5-2a11-413d-a219-dc9d5d9bf869.png)

**Desktop (please complete the following information):**
 - OS: Artix Linux 6.2.6-artix1-1 
 - Terminal: kitty
 - Version 0.9.2-10

**Comment by bpampel** [comment]
This are two separate issues (for each lyrics fetcher one) that likely already have solutions:
The genius one (displaying only "How to format…") was fixed 2 years ago in this commit https://github.com/ncmpcpp/ncmpcpp/commit/df1c4d7d7dee601a580169873ddb675d773777a5 but there wasn't a release since.

The azlyrics (displaying an empty page) has a proposed fix in this PR: https://github.com/ncmpcpp/ncmpcpp/pull/544/commits/39fa659609255b92f555dd0ef359557c8d1ef45e

Sadly the maintainers don't seem to be really active anymore.

**Comment by arybczak** [comment]
Fetchers were fixed in 985bc09b5c61d67cd179b1a6562c5949da2f368d.
